### ISSUE TITLE
The plugin has stopped working on NodeBB 1.6.0

### ISSUE THREAD

**Issue by asamolion** [cwis-public/nodebb-plugin-merge-subtopics#2]
This is the error that is received.

`TypeError: Cannot read property 'push' of undefined
    at /home/osama/workspace/nodebb-plugin-merge-subtopics/index.js:13:9
    at Array.forEach (native)
    at /home/osama/workspace/nodebb-plugin-merge-subtopics/index.js:12:16
    at /home/osama/workspace/nodebb/src/categories.js:238:3
    at /home/osama/workspace/nodebb/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/osama/workspace/nodebb/node_modules/async/dist/async.js:998:13)
    at /home/osama/workspace/nodebb/node_modules/async/dist/async.js:906:16
    at /home/osama/workspace/nodebb/node_modules/async/dist/async.js:421:16
    at next (/home/osama/workspace/nodebb/node_modules/async/dist/async.js:5302:29)
    at /home/osama/workspace/nodebb/node_modules/async/dist/async.js:906:16
    at /home/osama/workspace/nodebb/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/home/osama/workspace/nodebb/node_modules/async/dist/async.js:998:13)
    at /home/osama/workspace/nodebb/node_modules/async/dist/async.js:906:16
    at /home/osama/workspace/nodebb/src/categories.js:258:12
    at nextTask (/home/osama/workspace/nodebb/node_modules/async/dist/async.js:5297:14)
    at next (/home/osama/workspace/nodebb/node_modules/async/dist/async.js:5304:9)
    at /home/osama/workspace/nodebb/node_modules/async/dist/async.js:906:16
    at Object.privileges.categories.filterCids (/home/osama/workspace/nodebb/src/privileges/categories.js:234:11)
    at /home/osama/workspace/nodebb/src/categories.js:250:26
    at nextTask (/home/osama/workspace/nodebb/node_modules/async/dist/async.js:5297:14)
    at next (/home/osama/workspace/nodebb/node_modules/async/dist/async.js:5304:9)
    at /home/osama/workspace/nodebb/node_modules/async/dist/async.js:906:16`

**Comment by asamolion** [comment]
Pull request for the updated fixed version:

https://github.com/cwis-public/nodebb-plugin-merge-subtopics/pull/3
